# Hello welcome to the config!

commands:
  fakeop:
    enabled: true
  fakeban:
    enabled: true
    message:
      - '&fYou are banned from this server.'
  rocket:
    enabled: true
    velocity: 15 # 0.4 Being a regular jump
  explode:
    enabled: true
    power: 10 # 4 being a tnt
    fire: true # Will there be fire in this explosion
  butterfingers:
    enabled: true
  fire:
    enabled: true
  lightning:
    enabled: true
  spamchat:
    enabled: true
  closeinventory:
    enabled: true
  weak:
    enabled: true
    amplifier: 255 # They literally couldn't hurt a fly (Above this number won't work)
    duration: 30
  creeper:
    enabled: true
  fake-join:
    enabled: true
    usernames:
      - 'PastelRobots'
      - 'Herobrine'
      - 'epicgamer123'
      - 'Notch'
  fakecrash:
    enabled: true
  flip:
    enabled: true
  pickpocket:
    enabled: true
  slap:
    enabled: true
    health: 4 # 1 Being half a heart

console:
  enabled-msg: true # Sends a message in console when the plugin turns on and off
  debug-mode: false # Only enable if there's an issue!